trainJetFinder.py $ttH_fakes_DIR/config/tensorflow/config_lep2tau2jeven > /dev/null &
trainJetFinder.py $ttH_fakes_DIR/config/tensorflow/config_lep2tau3jeven > /dev/null &
trainJetFinder.py $ttH_fakes_DIR/config/tensorflow/config_lephad2jeven  > /dev/null &
trainJetFinder.py $ttH_fakes_DIR/config/tensorflow/config_lephad3jeven  > /dev/null &
trainJetFinder.py $ttH_fakes_DIR/config/tensorflow/config_lephad4jeven  > /dev/null &
trainJetFinder.py $ttH_fakes_DIR/config/tensorflow/config_lep2tau2jodd  > /dev/null &
trainJetFinder.py $ttH_fakes_DIR/config/tensorflow/config_lep2tau3jodd  > /dev/null &
trainJetFinder.py $ttH_fakes_DIR/config/tensorflow/config_lephad2jodd   > /dev/null &
trainJetFinder.py $ttH_fakes_DIR/config/tensorflow/config_lephad3jodd   > /dev/null &
trainJetFinder.py $ttH_fakes_DIR/config/tensorflow/config_lephad4jodd   > /dev/null &
